apiVersion: v1
kind: ReplicationController
metadata:
  name: guacd-controller
spec:
  replicas: 1
  selector:
    app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
      - name: guacd
        image: docker.io/glyptodon/guacd
      nodeSelector:
        role: frontend
