apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: guacamole-mysql
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    app: guacamole-mysql
  template:
    metadata:
      labels:
        app: guacamole-mysql
    spec:
      containers:
      - name: mysql
        image: registry.access.redhat.com/openshift3/mysql-55-rhel7 
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: "/var/lib/mysql/data"
        env:
        - name: MYSQL_USER
          value: guacamole_user
        - name: MYSQL_PASSWORD
          value: guacamole_pass
        - name: MYSQL_DATABASE
          value: guacamole_db
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: claim-mysql
      nodeSelector:
        role: frontend
