apiVersion: v1
kind: ReplicationController
metadata:
  name: ssh-controller
spec:
  replicas: 1
  selector:
    app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
      - name: rhel-ssh-server
        image: rhel-ssh-server
        ports:
        - containerPort: 22
#      - name: rhel-ssh-tunnel
#        image: rhel-ssh-tunnel
#        ports:
#        - containerPort: 3389
      nodeSelector:
        role: frontend
