apiVersion: v1
kind: Service
metadata:
  name: ssh-service
spec:
  ports:
  - port: 22
    protocol: TCP
    name: rhel-ssh-server
#  - port: 3389
#    protocol: TCP
#    name: rhel-ssh-tunnel
  selector:
    app: ssh
  type: NodePort
