apiVersion: v1
kind: ReplicationController
metadata:
  name: xrdp-controller
spec:
  replicas: 1
  selector:
    app: xrdp
  template:
    metadata:
      labels:
        app: xrdp
    spec:
      containers:
      - name: centos-vnc
        image: docker.io/kevensen/centos-vnc-firefox
        ports:
        - containerPort: 5901
      - name: centos-xrdp
        image: docker.io/kevensen/centos-xrdp
        ports:
        - containerPort: 3389
      nodeSelector:
        role: backend
